CC = ../c--

run-hello:
	@$(CC) < hello.c
	@./a.out

run-variable:
	@$(CC) < variable.c
	@./a.out

run-statement:
	@$(CC) < statement.c
	@./a.out

run-arithmetic:
	@$(CC) < arithmetic.c
	@./a.out

run-fibonacci:
	@$(CC) < fibonacci.c
	@./a.out

run-qsort:
	@$(CC) < qsort.c
	@./a.out

.PHONY: clean
clean:
	$(RM) a.out a.out.s msg.out
